### ISSUE TITLE
Question: support for CSV

### ISSUE THREAD

**Issue by harrybiddle** [asg017/sqlite-lines#10]
I was excited to discover this project, as I often work with large CSV files, and have ended up writing a lot of messy Pandas code in order to be able to read them in line-by-line.

I was therefore quite disappointed to discover this:

> sqlite-lines isn't a great option for CSVs. Technically you can, but the moment your data has a \n character in a field or header, then you'll get corrupted results.

Could you comment on whether, if sqlite-lines was able to overcome the \n-in-a-header problem, it would be an improvement over CSV Virtual Tables? I don't know CSV Virtual Tables well enough to know whether it reads the whole CSV file. If there is a possible improvement, it should be possible to distinguish a real "\n" from one lying in a header by following the CSV standard parsing rules (i.e. whether we find ourselves in an unclosed pair of quotes or not).

**Comment by asg017** [comment]
Hey @harrybiddle ! Unfortunately there's a lot of work that goes into parsing CSV that's out of scope for this project. The official [CSV extension](https://www.sqlite.org/csv.html) should handle large CSVs just fine.

There's also the [vsv](https://github.com/nalgeon/sqlean/blob/main/docs/vsv.md) extension from the sqlean project that publishes pre-compiled binaries on their [download page](https://github.com/nalgeon/sqlean/releases/tag/0.15.2) (the `vsv.so`/`vsv.dylib`/`vsv.dll` files). It also can handle different delimiters which the "official" version cannot

Parsing CSVs are [notoriously hard](http://thomasburette.com/blog/2014/05/25/so-you-want-to-write-your-own-CSV-code/), so it would be pretty difficult to include that in sqlite-lines. It'll also have perf issues that would slow down parsing files quite a lot, so I'd recommend looking at the csv or vsv extensions instead.

**Comment by harrybiddle** [comment]
Thanks @asg017
