### ISSUE TITLE
Broken example notebook link in the README

### ISSUE THREAD

**Issue by simonw** [asg017/sqlite-lines#11]
This bit of the README:

> Check out [this Observable notebook](https://observablehq.com/@asg017/sqlite-lines-wasm) for the full demonstration. The [Releases page](https://github.com/asg017/sqlite-lines/releases) contains the JavaScript and WASM files.

The link to "this Observable notebook" goes to https://observablehq.com/@asg017/sqlite-lines-wasm which shows me this message:

> You either don’t have permission to view this notebook, or it doesn’t exist.

**Comment by asg017** [comment]
Thanks for filing! Just fixed, should be here https://observablehq.com/@asg017/introducing-sqlite-lines
